In [1]:
getwd()

[1] "C:/Users/qwe/Documents/GitHub/Py_Works/Coursera_The_R_Programming_Environment/week_1"

In [10]:
myfunc <- function(){
    x <- rnorm(100)
    mean(x)
}

In [16]:
myfunc()

[1] 0.003916379

In [15]:
second <- function(){
    x + rnorm(length(x))
}

In [13]:
second()

ERROR: Error in second(): object 'x' not found


In [18]:
x<- 1


In [19]:
print(x)

[1] 1


In [20]:
x

[1] 1

In [21]:
msg<- 'hello'

In [22]:
msg

[1] "hello"

In [23]:
x<- 1:20

In [24]:
x

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20

In [27]:
vector()

logical(0)

In [30]:
y <- 1L

In [31]:
y

[1] 1

In [32]:
x <- c(0.5, 0.6)

In [33]:
x

[1] 0.5 0.6

In [ ]:
x <- c()

In [34]:
x <- 0:6

In [35]:
class(x)

[1] "integer"

In [36]:
as.numeric(x)

[1] 0 1 2 3 4 5 6

In [37]:
class(x)

[1] "integer"

In [38]:
as.logical(x)

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

In [39]:
as.character(x)

[1] "0" "1" "2" "3" "4" "5" "6"

# List

In [40]:
x <- list(1,'a',TRUE, 1+4i)

In [41]:
x

[[1]]
[1] 1

[[2]]
[1] "a"

[[3]]
[1] TRUE

[[4]]
[1] 1+4i

# Matrix`

In [44]:
m <- matrix(nrow=3, ncol= 3)

In [45]:
m

[,1] [,2] [,3]
[1,] NA   NA   NA  
[2,] NA   NA   NA  
[3,] NA   NA   NA

In [46]:
dim(m)

[1] 3 3

In [49]:
m <- matrix(1:9, nrow=3, ncol= 3)

In [50]:
m

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [51]:
m <- 1:10
m

[1]  1  2  3  4  5  6  7  8  9 10

In [52]:
dim(m) <- c(2,5)

In [53]:
m

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

# cbind and rbind

In [54]:
x <- 1:3
y<- 10:12

In [55]:
cbind(x,y)

x y 
[1,] 1 10
[2,] 2 11
[3,] 3 12

In [56]:
x

[1] 1 2 3

In [57]:
rbind(x,y)

[,1] [,2] [,3]
x  1    2    3  
y 10   11   12

In [58]:
x <- 1:3
y<- 10:13

# Factors

In [60]:
x <- factor( c('yes','yes','no','yes','no') )
x

[1] yes yes no  yes no 
Levels: no yes

In [61]:
table(x)

x
 no yes 
  2   3 

In [62]:
unclass(x)

[1] 2 2 1 2 1
attr(,"levels")
[1] "no"  "yes"

In [65]:
x <- factor( c('yes','yes','no','yes','no'),
           levels=c('yes','no'))
x

[1] yes yes no  yes no 
Levels: yes no

In [66]:
unclass(x)

[1] 1 1 2 1 2
attr(,"levels")
[1] "yes" "no"

In [69]:
is.na()

ERROR: Error in x.is.na(): could not find function "x.is.na"


In [70]:
x <- c( 1,2, NA, 10, 3) 
is.na(x)

[1] FALSE FALSE  TRUE FALSE FALSE

In [71]:
is.nan(x)

[1] FALSE FALSE FALSE FALSE FALSE

In [72]:
x <- c( 1,2, NA, NaN, 10, 3) 
is.na(x)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

In [73]:
is.nan(x)

[1] FALSE FALSE FALSE  TRUE FALSE FALSE

In [74]:
x <- data.frame( foo= 1:4, bat = c(T,T,F,F))
x

foo bat  
1 1    TRUE
2 2    TRUE
3 3   FALSE
4 4   FALSE

In [75]:
nrow(x)

[1] 4

In [76]:
ncol(x)

[1] 2

In [80]:
x<- 1:3
names(x)

NULL

In [81]:
x

[1] 1 2 3

In [82]:
names(x) <- c('aa','ss','bb')

In [83]:
x

aa ss bb 
 1  2  3

In [84]:
names(x)

[1] "aa" "ss" "bb"

In [85]:
x<- list(a=1, b=2, c=3)
x

$a
[1] 1

$b
[1] 2

$c
[1] 3

In [86]:
m <- matrix(1:4, nrow=2, ncol=2)
dimnames(m)<- list(c('a','b'), c('c','d') )
m

c d
a 1 3
b 2 4

#  READ WRITE DATA

In [ ]:
data <- read.table('foo.txt')

In [ ]:
data <- read.csv('foo.txt')

In [ ]:
initial <- read.table('datatable.txt', nrows = 100)
classes <- sapply(initial, class)
tabAll <- read.table('datatable.txt',
                    colClasses = classes)

# dput, dump

# file gzfile bzfile url

In [ ]:
con <- file('foo.txt', 'r')
data <- read.csv(con)
close(con)

In [ ]:
con <- gzfile('foo.gz', 'r')
x <- readLines(con, 10)
x

In [ ]:
con <- url('https://www.jhsph.edu', 'r')
x <- readLines(con )
x

# subsetting

In [87]:
x <- c('a','b','c','d')

In [88]:
x[1]

[1] "a"

In [89]:
x[1:4]

[1] "a" "b" "c" "d"

In [90]:
x[ x> 'a']

[1] "b" "c" "d"

In [91]:
u <- x>'a'

In [92]:
u

[1] FALSE  TRUE  TRUE  TRUE

In [93]:
x[u]

[1] "b" "c" "d"

In [113]:
x <- list( foo= 1:4, bar = c(0.6, 4), baz= 'gege' )

In [107]:
x

$foo
[1] 1 2 3 4

$bar
[1] 0.6 4.0

In [108]:
x[1]

$foo
[1] 1 2 3 4

In [109]:
x[2]

$bar
[1] 0.6 4.0

In [110]:
x$bar

[1] 0.6 4.0

In [111]:
x[['bar']]

[1] 0.6 4.0

In [112]:
x['bar']

$bar
[1] 0.6 4.0

In [114]:
x[c(1,3)]

$foo
[1] 1 2 3 4

$baz
[1] "gege"

In [115]:
name <- 'foo'

In [116]:
x[[name]]

[1] 1 2 3 4

In [117]:
x$name

NULL

In [118]:
x$foo

[1] 1 2 3 4

In [119]:
x <- list(a= list(10,11,23) , bar = c(0.6, 4), baz= 'gege' )

In [120]:
x[[c(1,3)]]

[1] 23

In [121]:
x[[1]][[3]]

[1] 23

In [122]:
x[[c(2,1)]]

[1] 0.6

In [132]:
x <- matrix(1:6, 2, 3)
x[1,2]

[1] 3

In [135]:
x[2,3]

[1] 6

In [134]:
x

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [136]:
x[1,]

[1] 1 3 5

In [137]:
x[,3]

[1] 5 6

In [138]:
x[1,2, drop=FALSE]

[,1]
[1,] 3

In [140]:
x[1, ,drop=FALSE]

[,1] [,2] [,3]
[1,] 1    3    5

# Partial matching

In [141]:
x<- list(aardvark = 1:5)
x$a

[1] 1 2 3 4 5

In [142]:
x[['a']]

NULL

In [143]:
x[['a', exact = FALSE]]

[1] 1 2 3 4 5

# Removing NA

In [144]:
x<- c( 1,2, NA, 4, NA,5 )
bad<- is.na(x)
x[!bad]

[1] 1 2 4 5

In [145]:
bad

[1] FALSE FALSE  TRUE FALSE  TRUE FALSE

In [148]:
y <- c( 'a','b', 1,2, NA, 4 )


In [149]:
good <- complete.cases(x,y)

In [150]:
good

[1]  TRUE  TRUE FALSE  TRUE FALSE  TRUE

In [151]:
x[good]

[1] 1 2 4 5

In [152]:
y[good]

[1] "a" "b" "2" "4"

In [153]:
airquality[1:6, ]

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
5 NA     NA     14.3 56   5     5  
6 28     NA     14.9 66   5     6

In [154]:
good <- complete.cases( airquality )

In [155]:
airquality[good, ][1:6, ]

Ozone Solar.R Wind Temp Month Day
1 41    190      7.4 67   5     1  
2 36    118      8.0 72   5     2  
3 12    149     12.6 74   5     3  
4 18    313     11.5 62   5     4  
7 23    299      8.6 65   5     7  
8 19     99     13.8 59   5     8

In [156]:
x<- 1:4 ; y<- 6:9

In [157]:
x+y

[1]  7  9 11 13

In [158]:
x > 2

[1] FALSE FALSE  TRUE  TRUE

In [159]:
x * y 

[1]  6 14 24 36

In [160]:
x /y

[1] 0.1666667 0.2857143 0.3750000 0.4444444

In [161]:
x <- matrix(1:4, 2,2) ; y <- matrix(rep(10,4) , 2, 2)

In [162]:
x * y 

[,1] [,2]
[1,] 10   30  
[2,] 20   40

In [163]:
x/y

[,1] [,2]
[1,] 0.1  0.3 
[2,] 0.2  0.4

In [164]:
x %*% y 

[,1] [,2]
[1,] 40   40  
[2,] 60   60

In [165]:
install.packages("swirl")

also installing the dependencies 'desc', 'pkgbuild', 'rprojroot', 'pkgload', 'praise', 'rlang', 'bitops', 'testthat', 'RCurl'



package 'desc' successfully unpacked and MD5 sums checked
package 'pkgbuild' successfully unpacked and MD5 sums checked
package 'rprojroot' successfully unpacked and MD5 sums checked
package 'pkgload' successfully unpacked and MD5 sums checked
package 'praise' successfully unpacked and MD5 sums checked
package 'rlang' successfully unpacked and MD5 sums checked
package 'bitops' successfully unpacked and MD5 sums checked
package 'testthat' successfully unpacked and MD5 sums checked
package 'RCurl' successfully unpacked and MD5 sums checked
package 'swirl' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\qwe\AppData\Local\Temp\RtmpaUklhh\downloaded_packages


In [166]:
packageVersion("swirl")

[1] '2.4.4'

In [167]:
library(swirl)


| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.



In [168]:
install_from_swirl("R Programming")

Downloading: 46 MB      


| Course installed successfully!



In [169]:
ls

function (name, pos = -1L, envir = as.environment(pos), all.names = FALSE, 
    pattern, sorted = TRUE) 
{
    if (!missing(name)) {
        pos <- tryCatch(name, error = function(e) e)
        if (inherits(pos, "error")) {
            name <- substitute(name)
            if (!is.character(name)) 
                name <- deparse(name)
            warning(gettextf("%s converted to character string", 
                sQuote(name)), domain = NA)
            pos <- name
        }
    }
    all.names <- .Internal(ls(envir, all.names, sorted))
    if (!missing(pattern)) {
        if ((ll <- length(grep("[", pattern, fixed = TRUE))) && 
            ll != length(grep("]", pattern, fixed = TRUE))) {
            if (pattern == "[") {
                pattern <- "\\["
                warning("replaced regular expression pattern '[' by  '\\\\['")
            }
            else if (length(grep("[^\\\\]\\[<-", pattern))) {
                pattern <- sub("\\[<-", "\\\\\\[<-", pattern)
                warning("replaced '[<-' by '\\\\[<-' in regular expression pattern")
            }
        }
        grep(pattern, all.names, value = TRUE)
    }
    else all.names
}
<bytecode: 0x0000000027898378>
<environment: namespace:base>

In [170]:
dir

function (path = ".", pattern = NULL, all.files = FALSE, full.names = FALSE, 
    recursive = FALSE, ignore.case = FALSE, include.dirs = FALSE, 
    no.. = FALSE) 
.Internal(list.files(path, pattern, all.files, full.names, recursive, 
    ignore.case, include.dirs, no..))
<bytecode: 0x000000000cbd72d8>
<environment: namespace:base>

In [171]:
pwd

ERROR: Error in eval(expr, envir, enclos): object 'pwd' not found
