In [2]:
# numpy

In [3]:
import numpy as np

an_array = np.array([3,33,333])

print(type(an_array))

<class 'numpy.ndarray'>


In [4]:
print(an_array.shape)

(3,)


In [5]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [6]:
an_array[0] = 888

In [7]:
an_array

array([888,  33, 333])

In [10]:
another = np.array([ [11,12,13],[21,22,23] ])
print(another)

print("the shape is 2 rows, 3 columns", another.shape)

print("accessing elements [0,0], [0,1], [1,0] of the ndarray : ", another[0,0], another[0,1], another[1,0])

[[11 12 13]
 [21 22 23]]
the shape is 2 rows, 3 columns (2, 3)
accessing elements [0,0], [0,1], [1,0] of the ndarray :  11 12 21


In [11]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [13]:
ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [14]:
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [15]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [16]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.60206034 0.60936069]
 [0.87450399 0.51749835]]
