In [2]:
# numpy

In [3]:
import numpy as np

an_array = np.array([3,33,333])

print(type(an_array))

<class 'numpy.ndarray'>


In [4]:
print(an_array.shape)

(3,)


In [5]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [6]:
an_array[0] = 888

In [7]:
an_array

array([888,  33, 333])

In [10]:
another = np.array([ [11,12,13],[21,22,23] ])
print(another)

print("the shape is 2 rows, 3 columns", another.shape)

print("accessing elements [0,0], [0,1], [1,0] of the ndarray : ", another[0,0], another[0,1], another[1,0])

[[11 12 13]
 [21 22 23]]
the shape is 2 rows, 3 columns (2, 3)
accessing elements [0,0], [0,1], [1,0] of the ndarray :  11 12 21


In [11]:
ex1 = np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [13]:
ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [14]:
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [15]:
ex4 = np.ones((1,2))
print(ex4)

[[1. 1.]]


In [16]:
ex5 = np.random.random((2,2))
print(ex5)

[[0.60206034 0.60936069]
 [0.87450399 0.51749835]]


In [4]:
import numpy as np

In [5]:
an_array = np.array([ [11,12,13,14],[21,22,23,24], [31,32,33,34] ])


In [6]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


In [9]:
print("before:",an_array[0,1])
a_slice[0,0] = 1000
print("after:", an_array[0,1])

before: 1000
after: 1000


In [8]:
#to make copy but not changing

In [11]:
a_slice = np.array(an_array[:2, 1:3])
print(a_slice)

[[1000   13]
 [  22   23]]


In [12]:
print("before:",an_array[0,1])
a_slice[0,0] = 500
print("after:", an_array[0,1])

before: 1000
after: 1000


In [14]:
    an_array = np.array([ [11,12,13,14],[21,22,23,24], [31,32,33,34] ])
    print(an_array)


[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [15]:
row_rank1 = an_array[1, :]

print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


In [17]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


In [18]:
print()
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)



[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [30]:
import numpy as np

In [40]:
an_array = np.array([ [11,12,13,14],[21,22,23,24], [31,32,33,34], [41,42,43,44] ])
print(an_array)


[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [41]:
print("original array:")
print(an_array)

original array:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [42]:
col_indices = np.array([0, 1, 2, 0])
print("\nCol indices picked : ", col_indices)

row_indices = np.arange(4)
print("\nRows indices picked : ", row_indices)


Col indices picked :  [0 1 2 0]

Rows indices picked :  [0 1 2 3]


In [43]:
for row,col in zip(row_indices,col_indices):
    print(row, ",",col)

0 , 0
1 , 1
2 , 2
3 , 0


In [44]:
print("Values in the array at those indices: ", an_array[row_indices, col_indices])

Values in the array at those indices:  [11 22 33 41]


In [46]:
an_array[row_indices, col_indices] += 1000

print("\nChanged Array")
print(an_array)


Changed Array
[[1011   12   13   14]
 [  21 1022   23   24]
 [  31   32 1033   34]
 [1041   42   43   44]]


In [49]:
arr = np.array([ [11,12,13],[21,22,23],[31,32,33] ])
print(arr)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [51]:
arr[:2]

array([[11, 12, 13],
       [21, 22, 23]])

In [52]:
an_array = np.array([ [11,12],[21,22],[31,32] ])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [53]:
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [54]:
 print(an_array[filter])

[21 22 31 32]


In [55]:
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [56]:
an_array[an_array > 15]

array([21, 22, 31, 32])

In [58]:
an_array[(an_array > 20) & (an_array <30)]

array([21, 22])

In [59]:
an_array[an_array %2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


In [61]:
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [62]:
ex2 = np.array([11.0, 12.0])
print(ex2.dtype)

float64


In [63]:
ex3 = np.array([11, 21], dtype=np.int64)
print(ex3.dtype)

int64


In [64]:
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]


In [65]:
ex5 = np.array([11, 21], dtype=np.float64)
print(ex5.dtype)
print()
print(ex5)

float64

[11. 21.]


In [67]:
x = np.array([ [111,112],[121,122]], dtype=np.int)
y = np.array([ [211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [69]:
print(x+y)
print()
print(np.add(x, y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [70]:
print(x-y)
print()
print(np.subtract(x, y))


[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [71]:
print(x*y)
print()
print(np.multiply(x,y))


[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [73]:
print(np.sqrt(x))
print()
print()

print(np.sqrt(y))



[[10.53565375 10.58300524]
 [11.         11.04536102]]


[[14.52928078 14.56365339]
 [14.86943173 14.90301983]]


In [74]:
# exponent e**x
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [2]:
import numpy as np

In [3]:
arr = 10 * np.random.rand(2,5)
print(arr)

[[1.47795692 3.32099674 9.53894342 8.69246498 2.46439483]
 [6.09587767 2.80669662 3.10603205 2.60863091 6.51414253]]


In [4]:
    print(arr.mean())

4.662613667615472


In [5]:
print(arr.mean(axis = 1))

[5.09895138 4.22627596]


In [6]:
print(arr.mean(axis = 0))

[3.7869173  3.06384668 6.32248774 5.65054794 4.48926868]


In [7]:
print(arr.sum())

46.626136676154715


In [8]:
print(np.median(arr, axis = 1))

[3.32099674 3.10603205]


# Sorting:

In [9]:
unsorted = np.random.rand(10)
print(unsorted)


[6.93378563e-01 6.49695403e-01 4.69583815e-01 3.68248771e-01
 2.82860684e-01 3.31996703e-04 6.63207365e-01 2.91636322e-01
 8.60960873e-01 5.31426600e-01]


In [10]:
sorted = np.array(unsorted)
sorted.sort()

In [11]:
print(sorted)
print()
print(unsorted)

[3.31996703e-04 2.82860684e-01 2.91636322e-01 3.68248771e-01
 4.69583815e-01 5.31426600e-01 6.49695403e-01 6.63207365e-01
 6.93378563e-01 8.60960873e-01]

[6.93378563e-01 6.49695403e-01 4.69583815e-01 3.68248771e-01
 2.82860684e-01 3.31996703e-04 6.63207365e-01 2.91636322e-01
 8.60960873e-01 5.31426600e-01]


In [12]:
unsorted.sort()

print(unsorted)

[3.31996703e-04 2.82860684e-01 2.91636322e-01 3.68248771e-01
 4.69583815e-01 5.31426600e-01 6.49695403e-01 6.63207365e-01
 6.93378563e-01 8.60960873e-01]


# Finding Unique elements:

In [14]:
array = np.array([1,2,1,4,2,1,4,2])
print(np.unique(array))

[1 2 4]


# Set Operations with np.array data type:

In [15]:
s1 = np.array(["desk","chair","bulb"])
s2 = np.array(["lamp","bulb","chair"])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [16]:
print(np.intersect1d(s1, s2))

['bulb' 'chair']


In [17]:
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [19]:
print( np.setdiff1d(s1,s2))

['desk']


In [20]:
print( np.setdiff1d(s2,s1))

['lamp']


In [21]:
print(np.in1d(s1, s2))

[False  True  True]


# Broadcasting

In [3]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
add_rows = np.array([ 1, 0, 2])
print(add_rows)

[1 0 2]


In [5]:
y = start + add_rows
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [7]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [9]:
print(start)
print()
print(add_cols)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[0]
 [1]
 [2]
 [3]]


In [10]:
y = start + add_cols
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [11]:
add_scalar = np.array([1])
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
a = np.array([[0,0],[0,0]])
b1 = np.array([1,1])
b2 = 1

print(a+b1)
print()
print(a+b2)

[[1 1]
 [1 1]]

[[1 1]
 [1 1]]


# Speedtest

## ndarrays are space efficient and memory optimized

In [15]:
from numpy import arange
from timeit import Timer

size = 1000000
timeits = 1000

In [16]:
nd_array = arange(size)
print( type(nd_array) )

<class 'numpy.ndarray'>


In [17]:
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000963 seconds


In [22]:
a_list = list(range(size))
print(type(a_list))

<class 'list'>


In [24]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list" % (timer_list.timeit(timeits)/timeits))


print("Time taken by list: %f seconds" % (timer_list.timeit(timeits)/timeits))

AttributeError: 'list' object has no attribute 'timeit'

In [25]:
# timer expects the operation as a parameter, here we pass sum(a_list)
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list:  %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list:  0.076546 seconds


In [27]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
arr[0:1, 1:3]

array([[2, 3]])

In [29]:
arr[2,1:3]

array([10, 11])

In [33]:
arr[:1, 1:3]

array([[2, 3]])

In [32]:

arr[1,:1:3]

array([5])

In [34]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr[:2,]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
A = np.array([[1],[2]])
print(A)
print()
B = np.array([[1,2],[3,4]])
print(B)
#A + B

[[1]
 [2]]

[[1 2]
 [3 4]]


In [38]:
a = np.array([2, 3])
b1 = np.array([1])
b2 = 1 

In [ ]:
a+b1
a+b2