In [1]:
from keras.models import Sequential


Using TensorFlow backend.


In [2]:
# Classification template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [3]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')



In [4]:
dataset.head(15)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0           1    15634602  Hargrave          619    France  Female   42   
1           2    15647311      Hill          608     Spain  Female   41   
2           3    15619304      Onio          502    France  Female   42   
3           4    15701354      Boni          699    France  Female   39   
4           5    15737888  Mitchell          850     Spain  Female   43   
5           6    15574012       Chu          645     Spain    Male   44   
6           7    15592531  Bartlett          822    France    Male   50   
7           8    15656148    Obinna          376   Germany  Female   29   
8           9    15792365        He          501    France    Male   44   
9          10    15592389        H?          684    France    Male   27   
10         11    15767821    Bearce          528    France    Male   31   
11         12    15737173   Andrews          497     Spain    Male   24   
12         13    15632264       Kay          476    France  Female   34   
13         14    15691483      Chin          549    France  Female   25   
14         15    15600882     Scott          635     Spain  Female   35   

    Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0        2       0.00              1          1               1   
1        1   83807.86              1          0               1   
2        8  159660.80              3          1               0   
3        1       0.00              2          0               0   
4        2  125510.82              1          1               1   
5        8  113755.78              2          1               0   
6        7       0.00              2          1               1   
7        4  115046.74              4          1               0   
8        4  142051.07              2          0               1   
9        2  134603.88              1          1               1   
10       6  102016.72              2          0               0   
11       3       0.00              2          1               0   
12      10       0.00              2          1               0   
13       5       0.00              2          0               0   
14       7       0.00              2          1               1   

    EstimatedSalary  Exited  
0         101348.88       1  
1         112542.58       0  
2         113931.57       1  
3          93826.63       0  
4          79084.10       0  
5         149756.71       1  
6          10062.80       0  
7         119346.88       1  
8          74940.50       0  
9          71725.73       0  
10         80181.12       0  
11         76390.01       0  
12         26260.98       0  
13        190857.79       0  
14         65951.65       0

In [5]:
X = dataset.iloc[:, 3:13 ].values


In [6]:
y = dataset.iloc[:, 13].values


In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [8]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [9]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [10]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [11]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [12]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)



In [14]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [15]:
# ANN
classifier = Sequential()


In [16]:
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


Instructions for updating:
Colocations handled automatically by placer.


In [17]:
# Addind second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [18]:
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [19]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [20]:
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 7s 875us/step - loss: 0.5082 - acc: 0.7954
Epoch 2/100
8000/8000 [==============================] - 2s 264us/step - loss: 0.4262 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 248us/step - loss: 0.4191 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 247us/step - loss: 0.4113 - acc: 0.7972
Epoch 5/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.4037 - acc: 0.8279
Epoch 6/100
8000/8000 [==============================] - 2s 255us/step - loss: 0.3963 - acc: 0.8294
Epoch 7/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.3893 - acc: 0.8300
Epoch 8/100
8000/8000 [==============================] - 2s 256us/step - loss: 0.3838 - acc: 0.8351
Epoch 9/100
8000/8000 [==============================] - 2s 259us/step - loss: 0.3792 - acc: 0.8429
Epoch 10/100
8000/8000 [============================

8000/8000 [==============================] - 2s 249us/step - loss: 0.3459 - acc: 0.8589
Epoch 80/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.3463 - acc: 0.8577
Epoch 81/100
8000/8000 [==============================] - 2s 261us/step - loss: 0.3445 - acc: 0.8594
Epoch 82/100
8000/8000 [==============================] - 2s 266us/step - loss: 0.3458 - acc: 0.8580
Epoch 83/100
8000/8000 [==============================] - 2s 239us/step - loss: 0.3461 - acc: 0.8582
Epoch 84/100
8000/8000 [==============================] - 2s 240us/step - loss: 0.3449 - acc: 0.8601
Epoch 85/100
8000/8000 [==============================] - 2s 234us/step - loss: 0.3454 - acc: 0.8585
Epoch 86/100
8000/8000 [==============================] - 2s 242us/step - loss: 0.3457 - acc: 0.8595
Epoch 87/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.3454 - acc: 0.8579
Epoch 88/100
8000/8000 [==============================] - 2s 251us/step - loss: 0.3452 - acc: 0.8580
Epo

In [22]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred >0.5)

In [23]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [24]:
cm

array([[1487,  108],
       [ 185,  220]], dtype=int64)

In [25]:
(1487+220)/(2000)

0.8535